### PR TITLE
New effect: `Respect The Law` #206

### PR DESCRIPTION
**Pull request by gromchek**

### CODE REVIEW

**Comment by Jersukai** [comment]
Nice! I know this effect is a bit unfair because some missions have scripted wanted level. Is there an easy way to ignore the stars given by script?

**Comment by Lordmau5** [comment]
> Nice! I know this effect is a bit unfair because some missions have scripted wanted level. Is there an easy way to ignore the stars given by script?

In theory yes, but on the other hand, the effect isn't gonna last for 30 minutes so I'd say it's fine if missions aren't excluded.

Stuff like `Weapon Roulette` for example is gonna be a bit tricky for missions like `Tagging Up Turf` (mission fails when you lose the spray can)
___
Also @gromchek did you test the effect ingame?

You don't need a new build of the GUI for that - Grabbing the `Trilogy Chaos Mod (Debug)` artifact from one of the [Trilogy GUI Tool actions](https://github.com/gta-chaos-mod/Trilogy-GUI-Tool/actions/runs/3861512550), then heading to the Experimental tab will present a textbox that allows you to put in an effect ID that you can manually send over to the game:
image

~~(I'll add this to the Release build as well when in the Experimental tab)~~

I've added this to the normal build of the GUI as well. You just gotta head into File -> Experimental to unlock the Experimental tab.
In there you have the textbox and button available, too

**Comment by gromchek** [comment]
> Also @gromchek did you test the effect ingame?

Yes, I tested it. It's works fine. Started a new game, punch a cop and got immediately busted.
I can split this effect to 6 different effects.
`Respect The Law: 1 star` - get busted if player have 1 or more stars etc.
Also I can add an internal timer to check the wanted level not every tick but every 20-30 sec,

**Comment by Lordmau5** [comment]
Checking every frame is in itself not a major issue, the internal game scripts do that in some places, too, iirc.

Splitting it into separate effects makes it feel a bit.. crowded, so I'd say stick to this 1 star check

**Comment by gromchek** [comment]
I also thought that the player can be busted if there is a cop nearby.

**Comment by Lordmau5** [comment]
I'd still prefer if you could add the `CanSetPedState()` check before setting the ped state because otherwise that's being set every game tick.

It probably works fine in like 99% of case but I can think of a rare scenario where you might get busted "twice" if that makes somewhat sense...

**Pull request merged**
